language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  # need multi-os from travis before knowing if os x config is sane:
  allow_failures:
    - os: osx

osx_image: xcode61

before_install:
  # setup gcc 4.8:
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi

install:
  # install gcc 4.8
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "g++" ]; then export CC=/usr/bin/gcc-4.8 && export CXX=/usr/bin/g++-4.8; fi
  # install clang 3.4
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "clang++" ]; then sudo apt-get install -qq llvm-3.4 llvm-3.4-dev; fi
 
script:
  - mkdir build && cd build && ../src/configure --jobs=4 --prefix=../install && make -j4 install

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - csaunders@illumina.com


