language: cpp

compiler:
  - gcc
  - clang

before_install:
  # setup gcc 4.8:
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi

install:
  # install gcc 4.8
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "g++" ]; then export CC=/usr/bin/gcc-4.8 && export CXX=/usr/bin/g++-4.8; fi
  # install clang 3.4
  - if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "clang++" ]; then sudo apt-get install -qq llvm-3.4 llvm-3.4-dev; fi
  #- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi
 
script:
  - mkdir build && cd build && ../src/configure --jobs=4 --prefix=../install && make -j4 install

branches:
  only:
    - v0.23.x 

notifications:
  email:
    recipients:
      - csaunders@illumina.com
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always 

os:
  - linux
  # - osx

osx_image: xcode61
